#!/bin/bash

# Change the directory value and choose your editor
directory=$HOME/Documents/Outlines/Souvenirs
files=$(ls $directory)
edit=vim

memorize() {
    local path=$1
    local file=$(basename $path)
    local dirname=$(echo $file | awk -F'_' '{print $1}')
    local dirpath=$directory/$dirname

    if [[ ! -d $dirpath ]]; then
        mkdir $dirpath
    fi
    echo $dirpath
}

get_file_ext() {
    echo ${1##*.}
}

get_file_basename() {
    echo ${1%%.*}
}



# ARGUMENT PARSER 

# Print list of souvenirs
if [[ $# -eq 0 ]]; then
    nb=$(ls $directory | wc -l)
    ls -lrt1 $directory
    echo -e "\n$nb souvenirs"
fi

# Print the content of the souvenir file if it exists
if [[ -f $directory/$1 ]]; then
    for file in $files
    do
        if [[ $1 == $file || $1 == ${file%%.*} ]]; then
            cat $directory/$file
        fi
    done

# Usage: souvenir -e FILE
# Description: Edit the file
elif [[ $1 == -e ]]; then
    for file in $files
    do
        if [[ $file == $2 ]]; then
            $edit $directory/$file
        fi
    done

# Usage: souvenir -a FILE
# Description: Add an existing file
elif [[ $1 == -a && -f $2 ]]; then
    new_souvenir=`basename $2`
    category=$(memorize $directory/$new_souvenir)
    cat $2 >> $category/$new_souvenir
    echo "Enjoy the new souvenir."
    echo ";)"

# Usage: 
# Description: Create a file
elif [[ $1 == -a && ! -f $2 ]]; then
    new_souvenir=$2
    category=$(memorize $directory/$new_souvenir)
    $edit $category/$new_souvenir
    echo "New souvenir [$new_souvenir] created."
    echo ":)"

# Usage: souvenir -l SOUVENIR
# Description: List the souvenirs memorized (the directories)
elif [[ $1 == -l && -d $directory/$2 ]]; then
    ls -1 $directory/$2
fi
